<?php
      
define('REDIRECT_QUERY_STRING',
        $_SERVER['REDIRECT_QUERY_STRING']? $_SERVER['REDIRECT_QUERY_STRING'] : NULL);
define('REDIRECT_URL',$_SERVER['REDIRECT_'] ? $_SERVER['REDIRECT_']: NULL);
